agnostic_nms = True
augment = False
classes = [2, 5, 7]
conf_thres = 0.1
device = 'cpu'
imgsz = 1280
iou_thres = 0.45
names = 'data/coco.names'
output = 'inference/output'
save_txt = False
source = 'inference/images/C9.jpg'
update = False
view_img = False
weights = ['yolov5s.pt']
config_deepsort = "deep_sort_pytorch/configs/deep_sort.yaml"
dnn = True
half = True
visualize = False
max_det = 100

