# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_map2D(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("2D Map")
        self.resize(574, 395)
        self.layout_main = QtWidgets.QGridLayout(self)
        self.layout_main.setObjectName("layout_main")
        self.frame_cameras = QtWidgets.QFrame(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_cameras.sizePolicy().hasHeightForWidth())
        self.frame_cameras.setSizePolicy(sizePolicy)
        self.frame_cameras.setStyleSheet("background: black;")
        self.frame_cameras.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_cameras.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_cameras.setObjectName("frame_cameras")
        self.layout_main.addWidget(self.frame_cameras, 0, 0, 1, 1)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("2D Map", "2D Map"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_map2D()
    ui.show()
    sys.exit(app.exec_())
