# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout_info_car_group_box.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet("background: beige")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.qlabel_brand = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qlabel_brand.sizePolicy().hasHeightForWidth())
        self.qlabel_brand.setSizePolicy(sizePolicy)
        self.qlabel_brand.setMinimumSize(QtCore.QSize(0, 30))
        self.qlabel_brand.setMaximumSize(QtCore.QSize(16777215, 30))
        self.qlabel_brand.setStyleSheet("background: gray")
        self.qlabel_brand.setObjectName("qlabel_brand")
        self.gridLayout.addWidget(self.qlabel_brand, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setStyleSheet("background: gray")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1)
        self.qlabel_out_time = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qlabel_out_time.sizePolicy().hasHeightForWidth())
        self.qlabel_out_time.setSizePolicy(sizePolicy)
        self.qlabel_out_time.setMinimumSize(QtCore.QSize(0, 30))
        self.qlabel_out_time.setMaximumSize(QtCore.QSize(16777215, 30))
        self.qlabel_out_time.setStyleSheet("background: gray")
        self.qlabel_out_time.setObjectName("qlabel_out_time")
        self.gridLayout.addWidget(self.qlabel_out_time, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setStyleSheet("background: gray")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setStyleSheet("background: gray")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.qlabel_plate = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qlabel_plate.sizePolicy().hasHeightForWidth())
        self.qlabel_plate.setSizePolicy(sizePolicy)
        self.qlabel_plate.setMinimumSize(QtCore.QSize(0, 30))
        self.qlabel_plate.setMaximumSize(QtCore.QSize(16777215, 30))
        self.qlabel_plate.setStyleSheet("background: gray")
        self.qlabel_plate.setObjectName("qlabel_plate")
        self.gridLayout.addWidget(self.qlabel_plate, 1, 1, 1, 1)
        self.qlabel_frame = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qlabel_frame.sizePolicy().hasHeightForWidth())
        self.qlabel_frame.setSizePolicy(sizePolicy)
        self.qlabel_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.qlabel_frame.setStyleSheet("background: gray")
        self.qlabel_frame.setObjectName("qlabel_frame")
        self.gridLayout.addWidget(self.qlabel_frame, 0, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setStyleSheet("background: gray")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.qlabel_in_time = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qlabel_in_time.sizePolicy().hasHeightForWidth())
        self.qlabel_in_time.setSizePolicy(sizePolicy)
        self.qlabel_in_time.setMinimumSize(QtCore.QSize(0, 30))
        self.qlabel_in_time.setMaximumSize(QtCore.QSize(16777215, 30))
        self.qlabel_in_time.setStyleSheet("background: gray")
        self.qlabel_in_time.setObjectName("qlabel_in_time")
        self.gridLayout.addWidget(self.qlabel_in_time, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setStyleSheet("background: gray")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.qlabel_color = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qlabel_color.sizePolicy().hasHeightForWidth())
        self.qlabel_color.setSizePolicy(sizePolicy)
        self.qlabel_color.setMinimumSize(QtCore.QSize(0, 30))
        self.qlabel_color.setMaximumSize(QtCore.QSize(16777215, 30))
        self.qlabel_color.setStyleSheet("background: gray")
        self.qlabel_color.setObjectName("qlabel_color")
        self.gridLayout.addWidget(self.qlabel_color, 2, 1, 1, 1)
        self.qlabel_frame_other = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qlabel_frame_other.sizePolicy().hasHeightForWidth())
        self.qlabel_frame_other.setSizePolicy(sizePolicy)
        self.qlabel_frame_other.setStyleSheet("background: gray")
        self.qlabel_frame_other.setObjectName("qlabel_frame_other")
        self.gridLayout.addWidget(self.qlabel_frame_other, 0, 2, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "GroupBox"))
        self.qlabel_brand.setText(_translate("Form", "qlabel_brand"))
        self.label_6.setText(_translate("Form", "Out time"))
        self.qlabel_out_time.setText(_translate("Form", "Out time"))
        self.label_4.setText(_translate("Form", "Brand"))
        self.label.setText(_translate("Form", "Plate"))
        self.qlabel_plate.setText(_translate("Form", "qlabel_plate"))
        self.qlabel_frame.setText(_translate("Form", "frame"))
        self.label_5.setText(_translate("Form", "In time"))
        self.qlabel_in_time.setText(_translate("Form", "In time"))
        self.label_3.setText(_translate("Form", "Color"))
        self.qlabel_color.setText(_translate("Form", "qlabel_color"))
        self.qlabel_frame_other.setText(_translate("Form", "frame"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

